### ISSUE TITLE
update GH action actions/setup-python to v5

### ISSUE THREAD

**Issue by alexatkoverse** [schemathesis/action#8]
in action.yaml:

steps:
    - uses: actions/setup-python@v4
    - 
Test complains about using node 16 that is deprecated

"
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
"

Needs to be updated to 

- uses: actions/setup-python@v5

Thanks!

**Comment by Stranger6667** [comment]
Thanks for reporting! I’ll fix it soon + will setup dependabot to avoid similar issues in the future

**Comment by Stranger6667** [comment]
Resolved in `1.0.4`
